enhanced_lidar_slam_node:
  ros__parameters:
    # 帧配置
    map_frame: "map"
    lidar_frame: "livox_frame_front"
    odom_frame: "odom"
    
    # 点云处理参数
    voxel_size: 0.05                    
    max_correspondence_distance: 2.0    
    max_iteration: 50                   
    
    # 内存限制
    max_points_per_map: 2000000         
    max_keyframes: 50                   
    
    # 传感器使用开关 - 选择性启用
    use_imu: true                       
    use_gps: false                      
    use_odom: true                      
    
    # 输出配置
    save_format: "pcd"
    save_map_interval: 15.0             
    output_dir: "maps"
    
    # 退化检测参数
    degeneracy_threshold: 0.02          
    consecutive_degenerate_limit: 20    
    
    # 关键帧参数
    keyframe_distance_threshold: 0.5    
    keyframe_rotation_threshold: 0.05   
    
    # QoS配置
    qos_profile:
      reliability: "best_effort"
      history: "keep_all"               
      depth: 100                        

# RViz2配置
rviz2:
  ros__parameters:
    config_file: "rviz/10m_easy_mapping.rviz"